FROM python:3.12 as base

WORKDIR /app
ADD pyproject.toml .
ADD requirements.txt .
#RUN pip install . && rm pyproject.toml requirements.txt

# Create a virtual environment and install dependencies
RUN python -m venv /venv \
    && /venv/bin/pip install --upgrade pip \
    && /venv/bin/pip install . \
    && rm pyproject.toml requirements.txt

ENV PYTHONPATH=/app
ENV PATH="/venv/bin:$PATH"

ADD docs docs
ADD pr_agent pr_agent
ADD github_action/entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
